// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Box struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Price     string        `json:"price"`
	Img       string        `json:"img"`
	Star      sql.NullInt64 `json:"star"`
	Nonce     int64         `json:"nonce"`
	State     int64         `json:"state"`
	CreatedAt time.Time     `json:"created_at"`
}

type BoxNft struct {
	ID           int64     `json:"id"`
	BoxID        int64     `json:"box_id"`
	TokenID      int64     `json:"token_id"`
	AddressOwner string    `json:"address_owner"`
	CreatedAt    time.Time `json:"created_at"`
}

type BoxRandom struct {
	ID        int64     `json:"id"`
	Level     int64     `json:"level"`
	Percent   int64     `json:"percent"`
	BoxID     int64     `json:"box_id"`
	CreatedAt time.Time `json:"created_at"`
}

type TransactionWeapon struct {
	ID            int64     `json:"id"`
	WeaponID      int64     `json:"weapon_id"`
	TokenID       int64     `json:"token_id"`
	Hash          string    `json:"hash"`
	FromAddress   string    `json:"from_address"`
	ToAddress     string    `json:"to_address"`
	Price         int64     `json:"price"`
	TransactionAt time.Time `json:"transaction_at"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	ID            int64     `json:"id"`
	Nonce         int64     `json:"nonce"`
	PublicAddress string    `json:"public_address"`
	Username      string    `json:"username"`
	CreatedAt     time.Time `json:"created_at"`
}

type ViewWeapon struct {
	ID        int64           `json:"id"`
	Name      string          `json:"name"`
	Price     int64           `json:"price"`
	Type      int64           `json:"type"`
	Img       string          `json:"img"`
	Level     int64           `json:"level"`
	Star      int64           `json:"star"`
	Nonce     int64           `json:"nonce"`
	State     int64           `json:"state"`
	CreatedAt time.Time       `json:"created_at"`
	Abilities json.RawMessage `json:"abilities"`
	Stat      json.RawMessage `json:"stat"`
}

type Weapon struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Price     int64     `json:"price"`
	Type      int64     `json:"type"`
	Img       string    `json:"img"`
	Level     int64     `json:"level"`
	Star      int64     `json:"star"`
	Nonce     int64     `json:"nonce"`
	State     int64     `json:"state"`
	Block     bool      `json:"block"`
	CreatedAt time.Time `json:"created_at"`
}

type WeaponAbility struct {
	ID          int64     `json:"id"`
	WeaponID    int64     `json:"weapon_id"`
	Img         string    `json:"img"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Level       int64     `json:"level"`
	CreatedAt   time.Time `json:"created_at"`
}

type WeaponNft struct {
	ID           int64     `json:"id"`
	WeaponID     int64     `json:"weapon_id"`
	TokenID      int64     `json:"token_id"`
	AddressOwner string    `json:"address_owner"`
	CreatedAt    time.Time `json:"created_at"`
}

type WeaponStat struct {
	ID        int64     `json:"id"`
	WeaponID  int64     `json:"weapon_id"`
	Damage    string    `json:"damage"`
	Speed     string    `json:"speed"`
	Hp        string    `json:"hp"`
	Critical  string    `json:"critical"`
	CreatedAt time.Time `json:"created_at"`
}
